[package]
name = "virtualpipe"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "virtualpipe"
path = "app/src/main.rs"

[dependencies]
anyhow = "*"
slint  = { version = "1.14.1", default-features = false, features = ["serde", "backend-winit", "renderer-skia", "compat-1-2"] }
serde = "*"
serde_json = "*"
dirs = "*"