[package]
name = "virtualpipe"
version = "1.2.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
slint  = { version = "1.14.1", default-features = false, features = ["serde", "backend-winit", "renderer-skia", "compat-1-2"] }
serde = "1.0.228"
serde_json = "1.0.145"
dirs = "6"